apiVersion: v1
kind: Service
metadata:
  name: zynkly-backend-service
spec:
  selector:
    app: zynkly-backend
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30050