apiVersion: v1
kind: Secret
metadata:
  name: zynkly-secrets
type: Opaque
# stringData allows passing plain text values instead of base64 encoding them 
# (they are converted to base64 automatically by Kubernetes)
# DO NOT COMMIT ACTUAL SECRETS TO VERSION CONTROL!
stringData:
  MONGO_URI: "mongodb+srv://anupdubeylpu_db_user:Qw0H8zG6ZKHJPIZY@cluster0.52plykm.mongodb.net/?appName=Cluster0"
  SESSION_SECRET: "your-super-strong-session-secret"
  GOOGLE_CLIENT_ID: "234857294769-858k19j2ai53qhluc04igoamk72lmtv0.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "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"
  FRONTEND_URL: "http://zynkly.dev"
  BACKEND_URL: "http://api.zynkly.dev"
  EMAIL_USER: "dubeyanupkumar349@gmail.com"
  EMAIL_PASS: "svrtpofkneeiyzwn"
  WHATSAPP_CLOUD_API_TOKEN: "your-whatsapp-token"
  WHATSAPP_PHONE_NUMBER_ID: "your-whatsapp-phone-id"
  WHATSAPP_ADMIN_NUMBER: "your-admin-number"
  ADMIN_EMAIL: "admin@gmail.com"
